INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (1, 'Paul McCarbine', 'Michael Kurd', 'Heart Failure', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox
Thu Apr 16 18:05:35 MSK 2020 Heart Failure Cured', 'Beta-blocker 25.0', null, 'CURED', '2020-04-16', '2020-04-16');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (4, 'Paul McCarbine', 'Michael Kurd', 'Heart Failure', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox

Thu Apr 23 19:22:54 MSK 2020 Heart Failure CURED', 'Beta-blocker 25.0', null, 'CURED', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (5, 'Imani Palmer', 'Michael Kurd', 'Heart Failure', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'Beta-blocker 25.0', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (6, 'Jamie Cain
', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox
', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (7, 'Tariq Warner', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox
', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (8, 'Marianne Pitts', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox
', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (9, 'Pia Barclay', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (10, 'Kaylee Cortez', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (11, 'Cruz Humphrey', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (12, 'Madeeha Jensen', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (13, 'Emile Beech', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (14, 'Eshaan Rooney', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (15, 'Suleman Charlton', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (16, 'Tabitha Rios', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (17, 'Manha Gilliam', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (18, 'Luca Gordon', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (19, 'Sophia Thornton', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (20, 'Elin Dejesus', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (21, 'Macaulay Potts', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (22, 'Shereen Rosales', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (23, 'Ismail Findlay', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (24, 'Faiza Duggan', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (25, 'Aleksandra Lynn', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (26, 'Alexandra Hale', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (27, 'Harlen Kelley', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (28, 'Aleisha O''Sullivan', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (29, 'Mae Herrera', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (30, 'Kylo Mcneil', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (31, 'Hanna Beltran', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (32, 'Yaseen Mcbride', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (33, 'Haaris Benton', 'Michael Kurd', 'No diagnose', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox', 'No treatment Course', null, 'DEAD', '2020-04-23', '2020-04-23');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (34, 'Phil Pull', 'Virus Savir', 'COVID-19', 'Height = 171, Weight = 61.Sex = M.
Sun May 03 18:33:21 MSK 2020 COVID-19 CURED', 'Antiviral EIDD-2801 20.0', null, 'CURED', '2020-03-01', '2020-05-03');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (35, 'Paul McCarbine', 'Virus Savir', 'Heart Failure', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox

Thu Apr 23 19:22:54 MSK 2020 Heart Failure CURED
Wed May 06 13:37:20 MSK 2020 Heart Failure GOOD', 'Beta-blocker 50.0', null, 'GOOD', '2020-04-26', '2020-05-06');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (36, 'Paul McCarbine', 'Virus Savir', 'Heart Failure', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox

Thu Apr 23 19:22:54 MSK 2020 Heart Failure CURED
Wed May 06 13:37:20 MSK 2020 Heart Failure GOOD
Wed May 06 17:15:44 MSK 2020 Heart Failure GOOD', 'Beta-blocker 30.0', null, 'GOOD', '2020-04-26', '2020-05-06');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (37, 'Paul McCarbine', 'Virus Savir', 'Heart Failure', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox

Thu Apr 23 19:22:54 MSK 2020 Heart Failure CURED
Wed May 06 13:37:20 MSK 2020 Heart Failure GOOD
Wed May 06 17:15:44 MSK 2020 Heart Failure GOOD
Wed May 06 17:25:20 MSK 2020 Heart Failure GOOD', 'Beta-blocker 25.0', null, 'GOOD', '2020-04-26', '2020-05-06');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (38, 'Paul McCarbine', 'Virus Savir', 'Heart Failure', 'Height = 180 cm, weight = 78kg.Sex = M. Had chicken pox

Thu Apr 23 19:22:54 MSK 2020 Heart Failure CURED
Wed May 06 13:37:20 MSK 2020 Heart Failure GOOD
Wed May 06 17:15:44 MSK 2020 Heart Failure GOOD
Wed May 06 17:25:20 MSK 2020 Heart Failure GOOD
Wed May 06 17:43:08 MSK 2020 Heart Failure CURED', 'Beta-blocker 23.0', null, 'CURED', '2020-04-26', '2020-05-06');
INSERT INTO hospital.discharged_patient (id, patient_name, doctor_name, diagnose, card_history, treatment_course, operation_name, patient_status, enrollment_date, discharge_date) VALUES (39, 'ProTester TesterPro', 'Michael Kurd', 'Heart Failure', 'M
Thu May 07 13:20:42 MSK 2020 Heart Failure CURED', 'Beta-blocker 23.0', null, 'CURED', '2020-05-07', '2020-05-07');