INSERT INTO hospital.speciality (id, speciality_name) VALUES (19, 'Anesthesiologist');
INSERT INTO hospital.speciality (id, speciality_name) VALUES (7, 'Cardiologist');
INSERT INTO hospital.speciality (id, speciality_name) VALUES (8, 'Dermatologist');
INSERT INTO hospital.speciality (id, speciality_name) VALUES (9, 'Endocrinologist');
INSERT INTO hospital.speciality (id, speciality_name) VALUES (1, 'Family Physician');
INSERT INTO hospital.speciality (id, speciality_name) VALUES (10, 'Gastroenterologist');
INSERT INTO hospital.speciality (id, speciality_name) VALUES (11, 'Infectious Disease Physician');
INSERT INTO hospital.speciality (id, speciality_name) VALUES (2, 'Internal Medicine Physician');
INSERT INTO hospital.speciality (id, speciality_name) VALUES (12, 'Nephrologist');
INSERT INTO hospital.speciality (id, speciality_name) VALUES (16, 'Neurologist');
INSERT INTO hospital.speciality (id, speciality_name) VALUES (4, 'Obstetrician/Gynecologist');
INSERT INTO hospital.speciality (id, speciality_name) VALUES (20, 'Oncologist');
INSERT INTO hospital.speciality (id, speciality_name) VALUES (13, 'Ophthalmologist');
INSERT INTO hospital.speciality (id, speciality_name) VALUES (14, 'Otolaryngologist');
INSERT INTO hospital.speciality (id, speciality_name) VALUES (3, 'Pediatrician');
INSERT INTO hospital.speciality (id, speciality_name) VALUES (17, 'Physician Executive');
INSERT INTO hospital.speciality (id, speciality_name) VALUES (6, 'Psychiatrist');
INSERT INTO hospital.speciality (id, speciality_name) VALUES (15, 'Pulmonologist');
INSERT INTO hospital.speciality (id, speciality_name) VALUES (18, 'Radiologist');
INSERT INTO hospital.speciality (id, speciality_name) VALUES (5, 'Surgeon');
INSERT INTO hospital.speciality (id, speciality_name) VALUES (21, 'Virologist');