INSERT INTO hospital.department (id, department_name, chamber_amount, vipChamber_amount) VALUES (1, 'Reception Department of therapy', 4, 1);
INSERT INTO hospital.department (id, department_name, chamber_amount, vipChamber_amount) VALUES (2, 'Pulmonology Department', 3, 1);
INSERT INTO hospital.department (id, department_name, chamber_amount, vipChamber_amount) VALUES (3, 'Rheumatology Department', 5, 1);
INSERT INTO hospital.department (id, department_name, chamber_amount, vipChamber_amount) VALUES (4, 'Cardiology department', 4, 0);
INSERT INTO hospital.department (id, department_name, chamber_amount, vipChamber_amount) VALUES (5, 'Gastroenterology department', 5, 2);
INSERT INTO hospital.department (id, department_name, chamber_amount, vipChamber_amount) VALUES (6, 'Traumatological and orthopedic Department', 5, 1);
INSERT INTO hospital.department (id, department_name, chamber_amount, vipChamber_amount) VALUES (7, 'Surgical department', 5, 2);
INSERT INTO hospital.department (id, department_name, chamber_amount, vipChamber_amount) VALUES (8, 'Department of anesthesiology and intensive care', 8, 0);
INSERT INTO hospital.department (id, department_name, chamber_amount, vipChamber_amount) VALUES (9, 'Gynecology department', 3, 2);
INSERT INTO hospital.department (id, department_name, chamber_amount, vipChamber_amount) VALUES (10, 'The maternity unit', 5, 2);
INSERT INTO hospital.department (id, department_name, chamber_amount, vipChamber_amount) VALUES (11, 'Obstetric physiology Department', 5, 1);
INSERT INTO hospital.department (id, department_name, chamber_amount, vipChamber_amount) VALUES (12, 'Department for newborns', 4, 1);
INSERT INTO hospital.department (id, department_name, chamber_amount, vipChamber_amount) VALUES (13, 'Department of anesthesiology and resuscitation of obstetric and gynecological service', 5, 0);
INSERT INTO hospital.department (id, department_name, chamber_amount, vipChamber_amount) VALUES (14, 'Department of anesthesiology and resuscitation for newborns', 4, 0);
INSERT INTO hospital.department (id, department_name, chamber_amount, vipChamber_amount) VALUES (15, 'Department of Traumatology', 3, 1);
INSERT INTO hospital.department (id, department_name, chamber_amount, vipChamber_amount) VALUES (16, 'X-ray Department', 0, 0);
INSERT INTO hospital.department (id, department_name, chamber_amount, vipChamber_amount) VALUES (17, 'The endoscopy Department', 1, 0);
INSERT INTO hospital.department (id, department_name, chamber_amount, vipChamber_amount) VALUES (18, 'Centralized sterilization Department', 5, 3);
INSERT INTO hospital.department (id, department_name, chamber_amount, vipChamber_amount) VALUES (19, 'Department of Virology', 7, 2);